// Auto-generated by scripts used to build the Play page from the /Play
// folder. Re-run that script if /Play's contents change; don't hand-edit.

export type PlayItemType = "image" | "video" | "pdf"

export interface PlayItem {
    src: string
    type: PlayItemType
    name: string
}

export interface PlayCategory {
    title: string
    slug: string
    items: PlayItem[]
}

export const PLAY_CATEGORIES: PlayCategory[] = [
    {
        "title": "Community Standards & Student Conduct Posts",
        "slug": "community-standards-and-student-conduct-posts",
        "items": [
            {
                "src": "/images/play/community-standards-and-student-conduct-posts/1.jpg",
                "type": "image",
                "name": "AIW 25 schedule-18"
            },
            {
                "src": "/images/play/community-standards-and-student-conduct-posts/2.jpg",
                "type": "image",
                "name": "AIW 25-15"
            },
            {
                "src": "/images/play/community-standards-and-student-conduct-posts/3.jpg",
                "type": "image",
                "name": "AIW x coe revised-05"
            },
            {
                "src": "/images/play/community-standards-and-student-conduct-posts/4.jpg",
                "type": "image",
                "name": "Intl Womens Day-36"
            },
            {
                "src": "/images/play/community-standards-and-student-conduct-posts/5.jpg",
                "type": "image",
                "name": "Welcome back"
            },
            {
                "src": "/images/play/community-standards-and-student-conduct-posts/6.jpg",
                "type": "image",
                "name": "wellbeing-10"
            }
        ]
    },
    {
        "title": "Hazing Prevention",
        "slug": "hazing-prevention",
        "items": [
            {
                "src": "/images/play/hazing-prevention/1.webp",
                "type": "image",
                "name": "Hazing Prevention 1"
            },
            {
                "src": "/images/play/hazing-prevention/2.jpg",
                "type": "image",
                "name": "Daily ad"
            },
            {
                "src": "/images/play/hazing-prevention/3.jpg",
                "type": "image",
                "name": "HPW half sheet"
            },
            {
                "src": "/images/play/hazing-prevention/4.png",
                "type": "image",
                "name": "Screenshot 2026-08-14 at 4.28.27 PM"
            },
            {
                "src": "/images/play/hazing-prevention/5.webp",
                "type": "image",
                "name": "Hazing Prevention 5"
            }
        ]
    },
    {
        "title": "MUSE",
        "slug": "muse",
        "items": [
            {
                "src": "/images/play/muse/1.jpg",
                "type": "image",
                "name": "Audrey Phan FINAL MUSE Calendar"
            },
            {
                "src": "/images/play/muse/2.jpg",
                "type": "image",
                "name": "DinnerIsServed Page 2"
            },
            {
                "src": "/images/play/muse/3.jpg",
                "type": "image",
                "name": "FlamesToAshes Page 2"
            }
        ]
    },
    {
        "title": "NewJeans Magazine",
        "slug": "newjeans-magazine",
        "items": [
            {
                "src": "/images/play/newjeans-magazine/1.jpg",
                "type": "image",
                "name": "NJ Magazine all"
            },
            {
                "src": "/images/play/newjeans-magazine/2.jpg",
                "type": "image",
                "name": "NJ Magazine back"
            },
            {
                "src": "/images/play/newjeans-magazine/3.jpg",
                "type": "image",
                "name": "NJ Magazine dani"
            },
            {
                "src": "/images/play/newjeans-magazine/4.jpg",
                "type": "image",
                "name": "NJ Magazine front and back"
            },
            {
                "src": "/images/play/newjeans-magazine/5.jpg",
                "type": "image",
                "name": "NJ Magazine front"
            },
            {
                "src": "/images/play/newjeans-magazine/6.jpg",
                "type": "image",
                "name": "NJ Magazine haerin"
            },
            {
                "src": "/images/play/newjeans-magazine/7.jpg",
                "type": "image",
                "name": "NJ Magazine hanni"
            },
            {
                "src": "/images/play/newjeans-magazine/8.jpg",
                "type": "image",
                "name": "NJ Magazine hyein"
            },
            {
                "src": "/images/play/newjeans-magazine/9.jpg",
                "type": "image",
                "name": "NJ Magazine minji"
            }
        ]
    },
    {
        "title": "Pho King",
        "slug": "pho-king",
        "items": [
            {
                "src": "/images/play/pho-king/1.png",
                "type": "image",
                "name": "Pho King 1"
            },
            {
                "src": "/images/play/pho-king/2.png",
                "type": "image",
                "name": "Pho King 2"
            },
            {
                "src": "/images/play/pho-king/3.jpg",
                "type": "image",
                "name": "Pho King 3"
            },
            {
                "src": "/images/play/pho-king/4.png",
                "type": "image",
                "name": "Pho King 4"
            },
            {
                "src": "/images/play/pho-king/5.jpg",
                "type": "image",
                "name": "Pho King 5"
            },
            {
                "src": "/images/play/pho-king/6.png",
                "type": "image",
                "name": "Pho King 6"
            },
            {
                "src": "/images/play/pho-king/7.png",
                "type": "image",
                "name": "Pho King 7"
            },
            {
                "src": "/images/play/pho-king/8.jpg",
                "type": "image",
                "name": "Pho King 8"
            },
            {
                "src": "/images/play/pho-king/9.png",
                "type": "image",
                "name": "Pho King 9"
            },
            {
                "src": "/images/play/pho-king/10.mp4",
                "type": "video",
                "name": "Untitled design"
            }
        ]
    },
    {
        "title": "Sputnik",
        "slug": "sputnik",
        "items": [
            {
                "src": "/images/play/sputnik/1.jpg",
                "type": "image",
                "name": "Sputnik 2"
            },
            {
                "src": "/images/play/sputnik/2.jpg",
                "type": "image",
                "name": "Sputnik 5"
            },
            {
                "src": "/images/play/sputnik/3.jpg",
                "type": "image",
                "name": "Sputnik 6"
            }
        ]
    },
    {
        "title": "VSA Instagram Posts",
        "slug": "vsa-instagram-posts",
        "items": [
            {
                "src": "/images/play/vsa-instagram-posts/1.png",
                "type": "image",
                "name": "GM 00 pink!"
            },
            {
                "src": "/images/play/vsa-instagram-posts/2.png",
                "type": "image",
                "name": "GM 1 final"
            },
            {
                "src": "/images/play/vsa-instagram-posts/3.png",
                "type": "image",
                "name": "GM 11"
            },
            {
                "src": "/images/play/vsa-instagram-posts/4.png",
                "type": "image",
                "name": "GM 3 final"
            },
            {
                "src": "/images/play/vsa-instagram-posts/5.jpg",
                "type": "image",
                "name": "GM 5"
            },
            {
                "src": "/images/play/vsa-instagram-posts/6.jpg",
                "type": "image",
                "name": "GM 6"
            },
            {
                "src": "/images/play/vsa-instagram-posts/7.jpg",
                "type": "image",
                "name": "GM 7-01"
            },
            {
                "src": "/images/play/vsa-instagram-posts/8.jpg",
                "type": "image",
                "name": "GM 8"
            },
            {
                "src": "/images/play/vsa-instagram-posts/9.jpg",
                "type": "image",
                "name": "GM 9"
            }
        ]
    },
    {
        "title": "VSA Merch",
        "slug": "vsa-merch",
        "items": [
            {
                "src": "/images/play/vsa-merch/1.png",
                "type": "image",
                "name": "Membership card VSA FINAL YAYY-03"
            },
            {
                "src": "/images/play/vsa-merch/2.png",
                "type": "image",
                "name": "membership post NEWSLETTER"
            },
            {
                "src": "/images/play/vsa-merch/3.png",
                "type": "image",
                "name": "vsa White Mockup back"
            }
        ]
    },
    {
        "title": "Misc",
        "slug": "misc",
        "items": [
            {
                "src": "/images/play/misc/1.png",
                "type": "image",
                "name": "Tyunning"
            }
        ]
    }
]
